### PR TITLE
Add support to some unofficial touchscreens

### PR DESCRIPTION
**Pull request by TBM13**
Added support to some unofficial touchscreens that are compatible with the Synaptics DSX I2C driver.

To enable this set `CONFIG_TOUCHSCREEN_SYNAPTICS_UNOFFICIAL` to y

### CODE REVIEW

**Comment by TBM13** [comment]
This time i used bool instead of tristate.

**Comment by feherneoh** [comment]
Thanks for correcting it, will do some testing with this to see if I can add some kind of detection, so we don't need separate binaries for the different panels

**Comment by TBM13** [comment]
Well, data[0] is always 0 in unofficial touchscreens like mine, so maybe we could use that.

**Comment by feherneoh** [comment]
Can you check what firmware build ID your digitizer reports, and what chip exactly it is?

I use this in synaptics_rmi4_query_device_info to get a build ID:
`dev_info(&rmi4_data->i2c_client->dev, "%s: Firmware: %02hX%02hX%02hX\n", __func__, rmi->build_id[2], rmi->build_id[1], rmi->build_id[0]);`

Also the chips I have are CG7720AM (seems to be fixed by your patch) and S2202B (both original and non-working fake)

If you have multiple digitizers at hand, I would greatly appreciate if you could provide data about as many of them as possible

**Comment by TBM13** [comment]
Will do, i had another device with unofficial touchscreen but i accidentally broke the digitizer itself.
If i'm not wrong, dung has one so i could ask him.

**Comment by TBM13** [comment]
Btw, in which devices are proximity sensor and ALS working?

**Comment by TBM13** [comment]
Bad news
[    4.940698] synaptics_rmi4_i2c 3-004b: synaptics_rmi4_query_device_info: Non-Synaptics device found, manufacturer ID = 0
[    4.951014] synaptics_rmi4_i2c 3-004b: synaptics_rmi4_query_device_info: Firmware: 000000

**Comment by feherneoh** [comment]
Proxy and ALS should work on all current A4L supported devices.

Doesn't those 2 lines get repeated with different values? I get manufacturer 128 after manufacturer 0

**Comment by TBM13** [comment]
Well, ALS isn't getting any data and proximity isn't working properly (tested in my 520)
I will give a look to see if these lines get repeated, but yesterday they weren't repeating.

**Comment by TBM13** [comment]
No, they are not repeating.

**Pull request closed without merging**
