### PR TITLE
 Merge branch 'cm-13.0_experimental' into cm-14.1

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by feherneoh** [comment]
Whoever our LOS-14.1 maintainer is, please check this

**Comment by ghost** [comment]
Checked. Your cm-14.1 maintainer is @r3pwn .
Off topic question: Does your new Kernel support sdcardfs?

**Comment by r3pwn** [comment]
I don't have write access to any of the repositories anymore, last time I checked.

**Comment by feherneoh** [comment]
@r3pwn I did not say "merge", just "check". If it's accepted, I'll merge it.
@trashmaster76 I'm planning to add sdcardfs support, but there will be zero progress on the new kernel as long as we don't have the new bootloader ready to be released

**Comment by ghost** [comment]
Here are more patches than needed because I and @r3pwn always cherry-picked so GitHub does not recognise some patches are already applied.
What's actually merged are your Wi-Fi and defconfig changes.
Why do you need a Wi-Fi patch? Are you using Lumia 720's NV bin for Lumia 520/525?

**Comment by r3pwn** [comment]
Lol, if you think it's okay to remove someone's write access and still expect them to contribute, like some kind of slave, you're sorely mistaken and now the community has to suffer because of your selfishness.

**Comment by feherneoh** [comment]
@r3pwn Sorry about being the one who has to clean up all the mess that is merged by others. I revoked the write rights after some members started to merge crap even into my "do-not-touch" tagged branches.
And you cannot deny that some members did actually merge commits those were not useful at all, untested, and even broke the whole tree many times.

**Comment by ghost** [comment]
That's why there are Pull Requests.
But I don't want to become impatient but can you please merge or close this. Thanks.

**Pull request merged**
